# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bureau"
ZSH_HIGHLIGHT_MAXLENGTH=100

# Timestamp shown in the history command output
HIST_STAMPS="yyyy-mm-dd"

# General aliases
alias lls="ls -aFhlG"
alias ll="ls -l"
alias ..="cd .."
alias ....="cd ../.."
alias g="git"

# React Native
alias rn-android="react-native run-android"
alias rn-android-menu="adb shell input keyevent 82"
alias rn-ios="react-native run-ios"
alias rn-start="react-native start"

# Android
alias adb-d="adb devices"
alias adb-r="adb reverse tcp:8081 tcp:8081 | echo 'adb : reverse tcp:8081'"

# Date
alias current_date='date "+%Y-%m-%d %H:%M:%S"'
alias current-date='current_date'

# Password generation
alias passgen="openssl rand -hex 15"

# Virtual Host listing
alias vhosts="apachectl -S | grep 'port 80\|alias\|default server'"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com; dig +short myip.opendns.com @resolver1.opendns.com | pbcopy"
alias iplocal="ipconfig getifaddr en1; ipconfig getifaddr en1 | pbcopy"
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"

# Shortcuts
alias histogrep='history | grep "$@"'
alias lazyp="~/zcripts/lazy-prettier.sh"

# Wazo.io
alias portalformat="git status -uno --porcelain | grep --color='never' '[A|M]' | cut -f3 -d' ' | xargs yarn format:file"
alias wdk-init="sh ~/zcripts/wazo.sh init"
alias wdk-push="sh ~/zcripts/wazo.sh push"
alias wdk-remove="sh ~/zcripts/wazo.sh remove"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="$PATH:$HOME/npm/bin" # Add Node to PATH for scripting

# Start SSH Forward agent
SSH_ENV=$HOME/.ssh/environment

# start the ssh-agent
function start_agent {
    echo "Initializing new SSH agent..."
    # spawn ssh-agent
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add
}

if [ -f "${SSH_ENV}" ]; then
     . "${SSH_ENV}" > /dev/null
     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi

